apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scalingpolicies.scalingpolicy.kope.io
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  group: scalingpolicy.kope.io
  versions:
    - name: v1alpha1
  names:
    kind: ScalingPolicy
    plural: scalingpolicies
  scope: Namespaced
